"""Database engine/session setup and first-run seed data.

Seeds exactly one `payors` row and the `atc_codes` rows this church
actually uses. Both are plain data, not code — editing a rate or adding a
second payor later is a DB update, not a deploy.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from decimal import Decimal

from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

from app.config import settings
from app.core.models import AtcCode, Base, Payor

# (code, description, default_rate) — verified against the real Favor Church
# "BIR 2307" sheet by cross-referencing the official BIR ATC schedule and
# empirically confirming tax_withheld / tax_base for every historical row
# using each code. See plan notes: WI050/WI051 deliberately differ from an
# unverified community source that used outdated pre-TRAIN-law thresholds.
SEED_ATC_CODES: list[tuple[str, str, str]] = [
    (
        "WI100",
        "Rentals (real/personal property, poles, satellites, "
        "transmission facilities, billboards) - individual payee",
        "0.05",
    ),
    (
        "WC100",
        "Rentals (real/personal property, poles, satellites, "
        "transmission facilities, billboards) - non-individual payee",
        "0.05",
    ),
    ("WC120", "Income payments to certain contractors", "0.02"),
    (
        "WC158",
        "Income payments to local/resident suppliers of goods "
        "(top withholding agents)",
        "0.01",
    ),
    (
        "WI160",
        "Income payments to local/resident suppliers of services "
        "(top withholding agents) - individual payee",
        "0.02",
    ),
    (
        "WC160",
        "Income payments to local/resident suppliers of services "
        "(top withholding agents) - non-individual payee",
        "0.02",
    ),
    (
        "WI050",
        "Management & technical consultants - individual, gross "
        "income for the current year did not exceed P3,000,000",
        "0.05",
    ),
    (
        "WI051",
        "Management & technical consultants - individual, gross "
        "income for the current year exceeds P3,000,000 or VAT-registered",
        "0.10",
    ),
]

# TIN/address are placeholders — this workbook never lists Favor Church's
# own TIN or registered address. MUST be replaced with real values (via a
# direct DB update) before any certificate generated by this app is issued.
SEED_PAYOR = {
    "tin": "000-000-000-000",
    "registered_name": "FAVOR CHURCH PH INC (PLACEHOLDER TIN - REPLACE BEFORE ISSUING CERTIFICATES)",
    "address": "PLACEHOLDER ADDRESS - REPLACE BEFORE ISSUING CERTIFICATES",
    "zip_code": None,
}

engine = create_engine(settings.database_url)
SessionLocal = sessionmaker(bind=engine, expire_on_commit=False)


def init_db() -> None:
    """Create all tables (if missing) and seed the payor + ATC codes (if empty).

    If `settings.demo_mode` is set, also seeds synthetic demo data (see
    `core/demo_seed.py`) — never used for the real deployment, and a no-op
    unless the database is completely empty.
    """
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    settings.uploads_dir.mkdir(parents=True, exist_ok=True)
    settings.generated_pdfs_dir.mkdir(parents=True, exist_ok=True)
    Base.metadata.create_all(engine)
    with SessionLocal() as session:
        _seed_atc_codes(session)
        _seed_payor(session)
        session.commit()

    if settings.demo_mode:
        from app.core.demo_seed import seed_demo_data

        with SessionLocal() as session:
            seed_demo_data(session)


def _seed_atc_codes(session: Session) -> None:
    existing = {code for (code,) in session.query(AtcCode.code).all()}
    for code, description, rate in SEED_ATC_CODES:
        if code not in existing:
            session.add(
                AtcCode(code=code, description=description, default_rate=Decimal(rate))
            )


def _seed_payor(session: Session) -> None:
    if session.query(Payor).count() == 0:
        session.add(Payor(**SEED_PAYOR))


@contextmanager
def get_session() -> Iterator[Session]:
    """Context-managed session for use outside Streamlit's cached-resource pattern."""
    session = SessionLocal()
    try:
        yield session
    finally:
        session.close()
